GROQ_API_KEY="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"



SMTP_EMAIL = "ktksultan09@gmail.com"
SMTP_PASSWORD = "exhz bjgy qqah vfiy"

SUPABASE_URL = "https://nylpzshnuausfuoudziw.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im55bHB6c2hudWF1c2Z1b3Vkeml3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3OTA0NjY3NDgsImV4cCI6MjEwNjA0Mjc0OH0.5ea7913HJKwQM5ZoUuhQ_8drR5rxpPdMpGhV2fk-0pg"
